# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: zamazzal <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/04 18:36:53 by zamazzal          #+#    #+#              #
#    Updated: 2018/10/04 21:10:57 by zamazzal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
FILES = display_file.c

.PHONY: all clean fclean

all:
	    @gcc -Wall -Wextra -Werror -o $(NAME) $(FILES)

clean:
	    @rm -f *.o

fclean: clean
	    @rm -f $(NAME)
